//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Immeubilier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Immeubilier()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int id_immeubiliers { get; set; }
        public float tarif_journaliere { get; set; }
        public float tarif_meusuelle { get; set; }
        public int nbr_chambre { get; set; }
        public string status { get; set; }
        public int id_categories { get; set; }
        public string description { get; set; }
        public string nom_proprietaire { get; set; }
        public string tel_proprietaire { get; set; }
        public float superficie { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
