//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quartier
    {
        public int id_quartiers { get; set; }
        public string libelle { get; set; }
        public int id_villes { get; set; }
    
        public virtual Ville Ville { get; set; }
    }
}
